#! /bin/sh

INCLUDE=include
SRC=src
TMP=lib42

if [ -e $TMP ]; then
	/bin/rm -fr $TMP
fi

LIST_OF_DIRECTORY=$(find . -type d -d 1)

/bin/mkdir $TMP
/bin/mkdir $TMP/$INCLUDE
/bin/mkdir $TMP/$SRC

for NAME_DIR in $LIST_OF_DIRECTORY
do
	LIST_OF_INCLUDE=$(find $NAME_DIR -type f -name "*.h")
	if [ $NAME_DIR == "./include" ]; then
		for FILE_H in $LIST_OF_INCLUDE
		do
			cp $FILE_H $TMP/$INCLUDE
		done
	else
		/bin/mkdir $TMP/$INCLUDE/$NAME_DIR
		for FILE_H in $LIST_OF_INCLUDE
		do
			cp $FILE_H $TMP/$INCLUDE/$NAME_DIR
		done
	fi
done

for FILE_C in $(find . -type f -name "*.c")
do
	cp $FILE_C $TMP/$SRC
done

LIST_OF_FILE_H=$(find $TMP/$INCLUDE -type f -name "*.h")

function	fix_header
{
	while [ ! -z "$1" ];
	do
		FILE_H=$(find $TMP/$INCLUDE -type f -name "*.h" -exec basename "{}" \;)
		for NAME_INCLUDE in $(/bin/cat $1 | grep "#include" | sed 's/#include <//g' | sed 's/>//g')
		do
			for PATTERN in $FILE_H
			do
				if [ $PATTERN == $NAME_INCLUDE ]; then
					DIR=$(echo $LIST_OF_FILE_H | tr ' ' '\n' | grep "$PATTERN" | sed 's/'$TMP'\/'$INCLUDE'\///g' | sed 's/\//\\\//g')
					CHANGE=$(echo "#include <$PATTERN>")
					TO=$(echo "#include <$DIR>")
					sed -i '' "s/$CHANGE/$TO/g" $1
				fi
			done
		done
		shift
	done
}

fix_header $(find $TMP/$SRC -type f -name "*.c")
fix_header $LIST_OF_FILE_H

cat ../../doc/misc/Makefile_part1.txt > $TMP/Makefile
printf "SRC\t\t=\t" >> $TMP/Makefile
SRC=$(find $TMP/$SRC -type f -name "*.c" | sed 's/'$TMP'\///g')
echo $SRC >> $TMP/Makefile
cat ../../doc/misc/Makefile_part2.txt >> $TMP/Makefile
